#!/usr/bin/env bash
# Script to change hostname resolutions in /etc/hosts
# Changes localhost to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts /etc/hosts.backup

sed -i 's/127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts

sed -i '/facebook\.com/d' /etc/hosts

echo "8.8.8.8 facebook.com" >> /etc/hosts