#!/usr/bin/env bash
# Script to change hostname resolutions in /etc/hosts

cp /etc/hosts /etc/hosts.backup

# Replace localhost + remove facebook.com in a temporary file
sed 's/127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts \
  | grep -v 'facebook\.com' > /tmp/hosts.new

# Add facebook.com and overwrite /etc/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts.new
cp /tmp/hosts.new /etc/hosts